// <auto-generated />
using System;
using DAM.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAM.Infrastructure.Migrations
{
    [DbContext(typeof(DeviceActivityDbContext))]
    [Migration("20251207135010_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("DAM.Core.Entities.DeviceActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExtractedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilesCopied")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilesDeleted")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FinalAvailableMB")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InitialAvailableMB")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("MegabytesCopied")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MegabytesDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecialEvent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalCapacityMB")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DeviceActivities");
                });

            modelBuilder.Entity("DAM.Core.Entities.ServiceEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ServiceEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
